platform :ios, '7.0'
pod 'RNFrostedSidebar', '~> 0.2.0'
pod 'CHTumblrMenu', '~> 0.1'
pod 'RNGridMenu', '~> 0.1.2'
pod 'RESideMenu', '~> 3.4'
pod "OHAttributedLabel"
pod "RMPickerViewController", "~> 1.0.0"
pod "AFNetworking"
pod "AVOSCloud"
pod "SVProgressHUD"
